---
name: 'Assign Issue to Volunteer'
on: [issue_comment]  # yamllint disable-line rule:truthy
permissions:
  issues: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: bhermann/issue-volunteer@v0.1.12
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'