---
name: Label Issues
on:
  issues:
    types:
      - opened
jobs:
  label_issues:
    if: github.repository_owner == 'CyberDrain'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label Issues
        uses: andymckay/labeler@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
          add-labels: 'not-assigned'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-if-assigned: true